student_management_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from student_management_app import views, HodViews, StaffViews, StudentViews
from student_management_app.EditResultVIewClass import EditResultViewClass
from student_management_system import settings

urlpatterns = [
                  path('demo', views.showDemoPage),
                  path('signup_admin', views.signup_admin, name="signup_admin"),
                  path('signup_student', views.signup_student, name="signup_student"),
                  path('signup_staff', views.signup_staff, name="signup_staff"),
                  path('do_admin_signup', views.do_admin_signup, name="do_admin_signup"),
                  path('do_staff_signup', views.do_staff_signup, name="do_staff_signup"),
                  path('do_signup_student', views.do_signup_student, name="do_signup_student"),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', views.ShowLoginPage, name="show_login"),
                  path('get_user_details', views.GetUserDetails),
                  path('logout_user', views.logout_user, name="logout"),
                  path('doLogin', views.doLogin, name="do_login"),
                  path('admin_home', HodViews.admin_home, name="admin_home"),
                  path('add_staff', HodViews.add_staff, name="add_staff"),
                  path('add_staff_save', HodViews.add_staff_save, name="add_staff_save"),
                  path('add_course', HodViews.add_course, name="add_course"),
                  path('add_course_save', HodViews.add_course_save, name="add_course_save"),
                  path('add_student', HodViews.add_student, name="add_student"),
                  path('add_student_save', HodViews.add_student_save, name="add_student_save"),
                  path('add_subject', HodViews.add_subject, name="add_subject"),
                  path('add_subject_save', HodViews.add_subject_save, name="add_subject_save"),
                  path('manage_staff', HodViews.manage_staff, name="manage_staff"),
                  path('manage_student', HodViews.manage_student, name="manage_student"),
                  path('manage_course', HodViews.manage_course, name="manage_course"),
                  path('manage_subject', HodViews.manage_subject, name="manage_subject"),
                  path('edit_staff/<str:staff_id>', HodViews.edit_staff, name="edit_staff"),
                  path('edit_staff_save', HodViews.edit_staff_save, name="edit_staff_save"),
                  path('edit_student/<str:student_id>', HodViews.edit_student, name="edit_student"),
                  path('edit_student_save', HodViews.edit_student_save, name="edit_student_save"),
                  path('edit_subject/<str:subject_id>', HodViews.edit_subject, name="edit_subject"),
                  path('edit_subject_save', HodViews.edit_subject_save, name="edit_subject_save"),
                  path('edit_course/<str:course_id>', HodViews.edit_course, name="edit_course"),
                  path('edit_course_save', HodViews.edit_course_save, name="edit_course_save"),
                  path('manage_session', HodViews.manage_session, name="manage_session"),
                  path('add_session_save', HodViews.add_session_save, name="add_session_save"),
                  path('check_email_exist', HodViews.check_email_exist, name="check_email_exist"),
                  path('check_username_exist', HodViews.check_username_exist, name="check_username_exist"),
                  path('student_feedback_message', HodViews.student_feedback_message, name="student_feedback_message"),
                  path('student_feedback_message_replied', HodViews.student_feedback_message_replied,
                       name="student_feedback_message_replied"),
                  path('staff_feedback_message', HodViews.staff_feedback_message, name="staff_feedback_message"),
                  path('staff_feedback_message_replied', HodViews.staff_feedback_message_replied,
                       name="staff_feedback_message_replied"),
                  path('student_leave_view', HodViews.student_leave_view, name="student_leave_view"),
                  path('staff_leave_view', HodViews.staff_leave_view, name="staff_leave_view"),
                  path('student_approve_leave/<str:leave_id>', HodViews.student_approve_leave,
                       name="student_approve_leave"),
                  path('student_disapprove_leave/<str:leave_id>', HodViews.student_disapprove_leave,
                       name="student_disapprove_leave"),
                  path('staff_disapprove_leave/<str:leave_id>', HodViews.staff_disapprove_leave,
                       name="staff_disapprove_leave"),
                  path('staff_approve_leave/<str:leave_id>', HodViews.staff_approve_leave, name="staff_approve_leave"),
                  path('admin_view_attendance', HodViews.admin_view_attendance, name="admin_view_attendance"),
                  path('admin_get_attendance_dates', HodViews.admin_get_attendance_dates,
                       name="admin_get_attendance_dates"),
                  path('admin_get_attendance_student', HodViews.admin_get_attendance_student,
                       name="admin_get_attendance_student"),
                  path('admin_profile', HodViews.admin_profile, name="admin_profile"),
                  path('admin_profile_save', HodViews.admin_profile_save, name="admin_profile_save"),
                  path('admin_send_notification_staff', HodViews.admin_send_notification_staff,
                       name="admin_send_notification_staff"),
                  path('admin_send_notification_student', HodViews.admin_send_notification_student,
                       name="admin_send_notification_student"),
                  path('send_student_notification', HodViews.send_student_notification,
                       name="send_student_notification"),
                  path('send_staff_notification', HodViews.send_staff_notification, name="send_staff_notification"),

                  #     Staff URL Path
                  path('staff_home', StaffViews.staff_home, name="staff_home"),
                  path('staff_take_attendance', StaffViews.staff_take_attendance, name="staff_take_attendance"),
                  path('staff_update_attendance', StaffViews.staff_update_attendance, name="staff_update_attendance"),
                  path('get_students', StaffViews.get_students, name="get_students"),
                  path('get_attendance_dates', StaffViews.get_attendance_dates, name="get_attendance_dates"),
                  path('get_attendance_student', StaffViews.get_attendance_student, name="get_attendance_student"),
                  path('save_updateattendance_data', StaffViews.save_updateattendance_data,
                       name="save_updateattendance_data"),
                  path('save_attendance_data', StaffViews.save_attendance_data, name="save_attendance_data"),
                  path('staff_apply_leave', StaffViews.staff_apply_leave, name="staff_apply_leave"),
                  path('staff_feedback', StaffViews.staff_feedback, name="staff_feedback"),
                  path('staff_feedback_save', StaffViews.staff_feedback_save, name="staff_feedback_save"),
                  path('staff_apply_leave_save', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
                  path('staff_profile', StaffViews.staff_profile, name="staff_profile"),
                  path('staff_profile_save', StaffViews.staff_profile_save, name="staff_profile_save"),
                  path('staff_fcmtoken_save', StaffViews.staff_fcmtoken_save, name="staff_fcmtoken_save"),
                  path('staff_all_notification', StaffViews.staff_all_notification, name="staff_all_notification"),
                  path('staff_add_result', StaffViews.staff_add_result, name="staff_add_result"),
                  path('save_student_result', StaffViews.save_student_result, name="save_student_result"),
                  path('edit_student_result', EditResultViewClass.as_view(), name="edit_student_result"),
                  path('fetch_result_student', StaffViews.fetch_result_student, name="fetch_result_student"),

                  path('student_view_attendance', StudentViews.student_view_attendance, name="student_view_attendance"),
                  path('student_view_attendance_post', StudentViews.student_view_attendance_post,
                       name="student_view_attendance_post"),
                  path('student_apply_leave', StudentViews.student_apply_leave, name="student_apply_leave"),
                  path('student_apply_leave_save', StudentViews.student_apply_leave_save,
                       name="student_apply_leave_save"),
                  path('student_feedback', StudentViews.student_feedback, name="student_feedback"),
                  path('student_feedback_save', StudentViews.student_feedback_save, name="student_feedback_save"),
                  path('student_home', StudentViews.student_home, name="student_home"),
                  path('student_profile', StudentViews.student_profile, name="student_profile"),
                  path('student_profile_save', StudentViews.student_profile_save, name="student_profile_save"),
                  path('student_fcmtoken_save', StudentViews.student_fcmtoken_save, name="student_fcmtoken_save"),
                  path('firebase-messaging-sw.js', views.showFirebaseJS, name="show_firebase_js"),
                  path('student_all_notification', StudentViews.student_all_notification,
                       name="student_all_notification"),
                  path('student_view_result', StudentViews.student_view_result, name="student_view_result"),

student_management_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class SessionYearModel(models.Model):
    id=models.AutoField(primary_key=True)
    session_start_year=models.DateField()
    session_end_year=models.DateField()
    object=models.Manager()

class CustomUser(AbstractUser):
    user_type_data=((1,"HOD"),(2,"Staff"),(3,"Student"))
    user_type=models.CharField(default=1,choices=user_type_data,max_length=10)

class AdminHOD(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class Staffs(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    fcm_token=models.TextField(default="")
    objects=models.Manager()

class Courses(models.Model):
    id=models.AutoField(primary_key=True)
    course_name=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


class Subjects(models.Model):
    id=models.AutoField(primary_key=True)
    subject_name=models.CharField(max_length=255)
    course_id=models.ForeignKey(Courses,on_delete=models.CASCADE,default=1)
    staff_id=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class Students(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    gender=models.CharField(max_length=255)
    profile_pic=models.FileField()
    address=models.TextField()
    course_id=models.ForeignKey(Courses,on_delete=models.DO_NOTHING)
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    fcm_token=models.TextField(default="")
    objects = models.Manager()

class Attendance(models.Model):
    id=models.AutoField(primary_key=True)
    subject_id=models.ForeignKey(Subjects,on_delete=models.DO_NOTHING)
    attendance_date=models.DateField()
    created_at=models.DateTimeField(auto_now_add=True)
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class AttendanceReport(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.DO_NOTHING)
    attendance_id=models.ForeignKey(Attendance,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class LeaveReportStudent(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.CASCADE)
    leave_date=models.CharField(max_length=255)
    leave_message=models.TextField()
    leave_status=models.IntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class LeaveReportStaff(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    leave_date = models.CharField(max_length=255)
    leave_message = models.TextField()
    leave_status = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackStudent(models.Model):
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackStaffs(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class NotificationStudent(models.Model):
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class NotificationStaffs(models.Model):
    id = models.AutoField(primary_key=True)
    staff_id = models.ForeignKey(Staffs, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class StudentResult(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.CASCADE)
    subject_id=models.ForeignKey(Subjects,on_delete=models.CASCADE)
    subject_exam_marks=models.FloatField(default=0)
    subject_assignment_marks=models.FloatField(default=0)
    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now_add=True)
    objects=models.Manager()

class OnlineClassRoom(models.Model):
    id=models.AutoField(primary_key=True)
    room_name=models.CharField(max_length=255)
    room_pwd=models.CharField(max_length=255)
    subject=models.ForeignKey(Subjects,on_delete=models.CASCADE)
    session_years=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    started_by=models.ForeignKey(Staffs,on_delete=models.CASCADE)
    is_active=models.BooleanField(default=True)
    created_on=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


@receiver(post_save,sender=CustomUser)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type==2:
            Staffs.objects.create(admin=instance,address="")
        if instance.user_type==3:
            Students.objects.create(admin=instance,course_id=Courses.objects.get(id=1),session_year_id=SessionYearModel.object.get(id=1),address="",profile_pic="",gender="")

@receiver(post_save,sender=CustomUser)
def save_user_profile(sender,instance,**kwargs):
    if instance.user_type==1:
        instance.adminhod.save()
    if instance.user_type==2:
        instance.staffs.save()
    if instance.user_type==3:
        instance.students.save()

student_management_app/templates/staff_template/all_notification.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Staff Notifications
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">


           <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">All Notifications</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Notifications</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for notification in notifications %}
                    <tr>
                      <td>{{ notification.message }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/staff_template/base_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>M.R.M High School |  Staff Panel</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "plugins/jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "plugins/summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    {% block custom_css %}{% endblock custom_css %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <h4 style="margin-left: 10px;margin-top: 5px;">M.R.M High School | Staff Panel</h4>
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          Logout
        </a>
      </li>
    </ul>

    <!-- Right navbar links -->
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
    {% include 'staff_template/sidebar_template.html' with user=user id=id %}

  <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
       <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
            </h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'staff_home' %}">Home</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
     {% block main_content %}{% endblock main_content %}

  </div>
  <!-- /.content-wrapper -->
    {% include 'staff_template/footer.html' %}

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "dist/js/demo.js" %}"></script>

{% block custom_js %}
{% endblock custom_js %}

</body>
</html>

student_management_app/templates/staff_template/edit_student_result.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Edit Results
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'edit_student_result' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Results</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                    {{ form }}
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Update Result</button>
                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_session_ids").change(function(){
            fetchStudents();
        });
        $("#id_subject_id").change(function(){
            fetchStudents();
        });

        $("#id_student_ids").change(function(){
            fetch_result_student();
        })

        function fetchStudents(){
            var session_year=$("#id_session_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:"{% url 'get_students' %}",
                type:'POST',
                data:{subject:subject,session_year:session_year},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data)
                var div_data="";
                for(key in json_data)
                {
                    div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
                }

                $("#id_student_ids").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }

        function fetch_result_student(){
            var id_student_ids=$("#id_student_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:"{% url 'fetch_result_student' %}",
                type:'POST',
                data:{subject_id:subject,student_id:id_student_ids},
            })
            .done(function(response){
                if(response=="False"){
                    alert("Result Not Found")
                }
                else{
                    var json_data=JSON.parse(response);
                    $("#id_assignment_marks").val(json_data['assign_marks'])
                    $("#id_exam_marks").val(json_data['exam_marks'])
                }

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }
    })
</script>
{% endblock custom_js %}

student_management_app/templates/staff_template/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2020-2021 <a href="https://github.com/isakkhar">Sakkhar.</a>.</strong>
    All rights reserved.
{#    <div class="float-right d-none d-sm-inline-block">#}
{#      <b>Version</b> 1.0#}
{#    </div>#}
  </footer>

student_management_app/templates/staff_template/staff_feedback.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Feedback Message
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Leave a Feedback Message</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
               <form action="{% url 'staff_feedback_save' %}" method="post">
                <div class="card-body">

                    {% csrf_token %}
                  <div class="form-group">
                    <label>Feedback Message</label>
                    <textarea class="form-control" rows="6" name="feedback_msg"></textarea>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Leave a Feedback Message</button>
                </div>
               </form>
            </div>

            <!-- /.card -->
           <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Feedback History</h3>
              </div>

               <div class="table">
               <table class="table">
                   <tr>
                       <th>ID</th>
                       <th>Feedback Message</th>
                       <th>Feedback Reply</th>
                   </tr>
                   {% for row in feedback_data %}
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.feedback }}</td>
                            <td>{{ row.feedback_reply }}</td>
                        </tr>
                   {% endfor %}
               </table>
               </div>
            </div>



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}