student_management_system/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from student_management_app import views, HodViews, StaffViews, StudentViews
from student_management_app.EditResultVIewClass import EditResultViewClass
from student_management_system import settings

urlpatterns = [
                  path('demo', views.showDemoPage),
                  path('signup_admin', views.signup_admin, name="signup_admin"),
                  path('signup_student', views.signup_student, name="signup_student"),
                  path('signup_staff', views.signup_staff, name="signup_staff"),
                  path('do_admin_signup', views.do_admin_signup, name="do_admin_signup"),
                  path('do_staff_signup', views.do_staff_signup, name="do_staff_signup"),
                  path('do_signup_student', views.do_signup_student, name="do_signup_student"),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', views.ShowLoginPage, name="show_login"),
                  path('get_user_details', views.GetUserDetails),
                  path('logout_user', views.logout_user, name="logout"),
                  path('doLogin', views.doLogin, name="do_login"),
                  path('admin_home', HodViews.admin_home, name="admin_home"),
                  path('add_staff', HodViews.add_staff, name="add_staff"),
                  path('add_staff_save', HodViews.add_staff_save, name="add_staff_save"),
                  path('add_course', HodViews.add_course, name="add_course"),
                  path('add_course_save', HodViews.add_course_save, name="add_course_save"),
                  path('add_student', HodViews.add_student, name="add_student"),
                  path('add_student_save', HodViews.add_student_save, name="add_student_save"),
                  path('add_subject', HodViews.add_subject, name="add_subject"),
                  path('add_subject_save', HodViews.add_subject_save, name="add_subject_save"),
                  path('manage_staff', HodViews.manage_staff, name="manage_staff"),
                  path('manage_student', HodViews.manage_student, name="manage_student"),
                  path('manage_course', HodViews.manage_course, name="manage_course"),
                  path('manage_subject', HodViews.manage_subject, name="manage_subject"),
                  path('edit_staff/<str:staff_id>', HodViews.edit_staff, name="edit_staff"),
                  path('edit_staff_save', HodViews.edit_staff_save, name="edit_staff_save"),
                  path('edit_student/<str:student_id>', HodViews.edit_student, name="edit_student"),
                  path('edit_student_save', HodViews.edit_student_save, name="edit_student_save"),
                  path('edit_subject/<str:subject_id>', HodViews.edit_subject, name="edit_subject"),
                  path('edit_subject_save', HodViews.edit_subject_save, name="edit_subject_save"),
                  path('edit_course/<str:course_id>', HodViews.edit_course, name="edit_course"),
                  path('edit_course_save', HodViews.edit_course_save, name="edit_course_save"),
                  path('manage_session', HodViews.manage_session, name="manage_session"),
                  path('add_session_save', HodViews.add_session_save, name="add_session_save"),
                  path('check_email_exist', HodViews.check_email_exist, name="check_email_exist"),
                  path('check_username_exist', HodViews.check_username_exist, name="check_username_exist"),
                  path('student_feedback_message', HodViews.student_feedback_message, name="student_feedback_message"),
                  path('student_feedback_message_replied', HodViews.student_feedback_message_replied,
                       name="student_feedback_message_replied"),
                  path('staff_feedback_message', HodViews.staff_feedback_message, name="staff_feedback_message"),
                  path('staff_feedback_message_replied', HodViews.staff_feedback_message_replied,
                       name="staff_feedback_message_replied"),
                  path('student_leave_view', HodViews.student_leave_view, name="student_leave_view"),
                  path('staff_leave_view', HodViews.staff_leave_view, name="staff_leave_view"),
                  path('student_approve_leave/<str:leave_id>', HodViews.student_approve_leave,
                       name="student_approve_leave"),
                  path('student_disapprove_leave/<str:leave_id>', HodViews.student_disapprove_leave,
                       name="student_disapprove_leave"),
                  path('staff_disapprove_leave/<str:leave_id>', HodViews.staff_disapprove_leave,
                       name="staff_disapprove_leave"),
                  path('staff_approve_leave/<str:leave_id>', HodViews.staff_approve_leave, name="staff_approve_leave"),
                  path('admin_view_attendance', HodViews.admin_view_attendance, name="admin_view_attendance"),
                  path('admin_get_attendance_dates', HodViews.admin_get_attendance_dates,
                       name="admin_get_attendance_dates"),
                  path('admin_get_attendance_student', HodViews.admin_get_attendance_student,
                       name="admin_get_attendance_student"),
                  path('admin_profile', HodViews.admin_profile, name="admin_profile"),
                  path('admin_profile_save', HodViews.admin_profile_save, name="admin_profile_save"),
                  path('admin_send_notification_staff', HodViews.admin_send_notification_staff,
                       name="admin_send_notification_staff"),
                  path('admin_send_notification_student', HodViews.admin_send_notification_student,
                       name="admin_send_notification_student"),
                  path('send_student_notification', HodViews.send_student_notification,
                       name="send_student_notification"),
                  path('send_staff_notification', HodViews.send_staff_notification, name="send_staff_notification"),

                  #     Staff URL Path
                  path('staff_home', StaffViews.staff_home, name="staff_home"),
                  path('staff_take_attendance', StaffViews.staff_take_attendance, name="staff_take_attendance"),
                  path('staff_update_attendance', StaffViews.staff_update_attendance, name="staff_update_attendance"),
                  path('get_students', StaffViews.get_students, name="get_students"),
                  path('get_attendance_dates', StaffViews.get_attendance_dates, name="get_attendance_dates"),
                  path('get_attendance_student', StaffViews.get_attendance_student, name="get_attendance_student"),
                  path('save_updateattendance_data', StaffViews.save_updateattendance_data,
                       name="save_updateattendance_data"),
                  path('save_attendance_data', StaffViews.save_attendance_data, name="save_attendance_data"),
                  path('staff_apply_leave', StaffViews.staff_apply_leave, name="staff_apply_leave"),
                  path('staff_feedback', StaffViews.staff_feedback, name="staff_feedback"),
                  path('staff_feedback_save', StaffViews.staff_feedback_save, name="staff_feedback_save"),
                  path('staff_apply_leave_save', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
                  path('staff_profile', StaffViews.staff_profile, name="staff_profile"),
                  path('staff_profile_save', StaffViews.staff_profile_save, name="staff_profile_save"),
                  path('staff_fcmtoken_save', StaffViews.staff_fcmtoken_save, name="staff_fcmtoken_save"),
                  path('staff_all_notification', StaffViews.staff_all_notification, name="staff_all_notification"),
                  path('staff_add_result', StaffViews.staff_add_result, name="staff_add_result"),
                  path('save_student_result', StaffViews.save_student_result, name="save_student_result"),
                  path('edit_student_result', EditResultViewClass.as_view(), name="edit_student_result"),
                  path('fetch_result_student', StaffViews.fetch_result_student, name="fetch_result_student"),

                  path('student_view_attendance', StudentViews.student_view_attendance, name="student_view_attendance"),
                  path('student_view_attendance_post', StudentViews.student_view_attendance_post,
                       name="student_view_attendance_post"),
                  path('student_apply_leave', StudentViews.student_apply_leave, name="student_apply_leave"),
                  path('student_apply_leave_save', StudentViews.student_apply_leave_save,
                       name="student_apply_leave_save"),
                  path('student_feedback', StudentViews.student_feedback, name="student_feedback"),
                  path('student_feedback_save', StudentViews.student_feedback_save, name="student_feedback_save"),
                  path('student_home', StudentViews.student_home, name="student_home"),
                  path('student_profile', StudentViews.student_profile, name="student_profile"),
                  path('student_profile_save', StudentViews.student_profile_save, name="student_profile_save"),
                  path('student_fcmtoken_save', StudentViews.student_fcmtoken_save, name="student_fcmtoken_save"),
                  path('firebase-messaging-sw.js', views.showFirebaseJS, name="show_firebase_js"),
                  path('student_all_notification', StudentViews.student_all_notification,
                       name="student_all_notification"),
                  path('student_view_result', StudentViews.student_view_result, name="student_view_result"),

student_management_app/forms.py
from django import forms
from django.forms import ChoiceField

from student_management_app.models import Courses, SessionYearModel, Subjects, Students

class ChoiceNoValidation(ChoiceField):
    def validate(self, value):
        pass

class DateInput(forms.DateInput):
    input_type = "date"

class AddStudentForm(forms.Form):
    email=forms.EmailField(label="Email",max_length=50,widget=forms.EmailInput(attrs={"class":"form-control","autocomplete":"off"}))
    password=forms.CharField(label="Password",max_length=50,widget=forms.PasswordInput(attrs={"class":"form-control"}))
    first_name=forms.CharField(label="First Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name=forms.CharField(label="Last Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    username=forms.CharField(label="Username",max_length=50,widget=forms.TextInput(attrs={"class":"form-control","autocomplete":"off"}))
    address=forms.CharField(label="Address",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    course_list=[]
    try:
        courses=Courses.objects.all()
        for course in courses:
            small_course=(course.id,course.course_name)
            course_list.append(small_course)
    except:
        course_list=[]
    #course_list=[]

    session_list = []
    try:
        sessions = SessionYearModel.object.all()

        for ses in sessions:
            small_ses = (ses.id, str(ses.session_start_year)+"   TO  "+str(ses.session_end_year))
            session_list.append(small_ses)
    except:
        session_list=[]

    gender_choice=(
        ("Male","Male"),
        ("Female","Female")
    )

    course=forms.ChoiceField(label="Course",choices=course_list,widget=forms.Select(attrs={"class":"form-control"}))
    sex=forms.ChoiceField(label="Sex",choices=gender_choice,widget=forms.Select(attrs={"class":"form-control"}))
    session_year_id=forms.ChoiceField(label="Session Year",choices=session_list,widget=forms.Select(attrs={"class":"form-control"}))
    profile_pic=forms.FileField(label="Profile Pic",max_length=50,widget=forms.FileInput(attrs={"class":"form-control"}))

class EditStudentForm(forms.Form):
    email=forms.EmailField(label="Email",max_length=50,widget=forms.EmailInput(attrs={"class":"form-control"}))
    first_name=forms.CharField(label="First Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name=forms.CharField(label="Last Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    username=forms.CharField(label="Username",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    address=forms.CharField(label="Address",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))


    course_list=[]
    try:
        courses = Courses.objects.all()
        for course in courses:
            small_course=(course.id,course.course_name)
            course_list.append(small_course)
    except:
        course_list=[]

    session_list = []
    try:
        sessions = SessionYearModel.object.all()

        for ses in sessions:
            small_ses = (ses.id, str(ses.session_start_year)+"   TO  "+str(ses.session_end_year))
            session_list.append(small_ses)
    except:
        pass
        #session_list = []

    gender_choice=(
        ("Male","Male"),
        ("Female","Female")
    )

    course=forms.ChoiceField(label="Course",choices=course_list,widget=forms.Select(attrs={"class":"form-control"}))
    sex=forms.ChoiceField(label="Sex",choices=gender_choice,widget=forms.Select(attrs={"class":"form-control"}))
    session_year_id=forms.ChoiceField(label="Session Year",choices=session_list,widget=forms.Select(attrs={"class":"form-control"}))
    profile_pic=forms.FileField(label="Profile Pic",max_length=50,widget=forms.FileInput(attrs={"class":"form-control"}),required=False)

class EditResultForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.staff_id=kwargs.pop("staff_id")
        super(EditResultForm,self).__init__(*args,**kwargs)
        subject_list=[]
        try:
            subjects=Subjects.objects.filter(staff_id=self.staff_id)
            for subject in subjects:
                subject_single=(subject.id,subject.subject_name)
                subject_list.append(subject_single)
        except:
            subject_list=[]
        self.fields['subject_id'].choices=subject_list

    session_list=[]
    try:
        sessions=SessionYearModel.object.all()
        for session in sessions:
            session_single=(session.id,str(session.session_start_year)+" TO "+str(session.session_end_year))
            session_list.append(session_single)
    except:
        session_list=[]

    subject_id=forms.ChoiceField(label="Subject",widget=forms.Select(attrs={"class":"form-control"}))
    session_ids=forms.ChoiceField(label="Session Year",choices=session_list,widget=forms.Select(attrs={"class":"form-control"}))
    student_ids=ChoiceNoValidation(label="Student",widget=forms.Select(attrs={"class":"form-control"}))
    assignment_marks=forms.CharField(label="Assignment Marks",widget=forms.TextInput(attrs={"class":"form-control"}))
    exam_marks=forms.CharField(label="Exam Marks",widget=forms.TextInput(attrs={"class":"form-control"}))

student_management_app/templates/hod_template/add_staff_template.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Add Staff
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Staff</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_staff_save" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address">
                  </div>
                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Add Staff</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_email").keyup(function(){
            var email=$(this).val();

           if(email!=""){
                $.ajax({
                    url:'{% url 'check_email_exist' %}',
                    type:'POST',
                    data:{email:email}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: red;font-weight: bold;'>Email Not Available</span>").insertAfter("#id_email");
                    }
                    else{
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: green;font-weight: bold;'>Email Available</span>").insertAfter("#id_email");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
              $(".email_error").remove();
            }

        });

        $("#id_username").keyup(function(){
            var username=$(this).val();

            if(username!=""){
                $.ajax({
                    url:'{% url 'check_username_exist' %}',
                    type:'POST',
                    data:{username:username}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: red;font-weight: bold;'>Username Not Available</span>").insertAfter("#id_username");
                    }
                    else{
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: green;font-weight: bold;'>Username Available</span>").insertAfter("#id_username");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
                $(".username_error").remove();
            }

        });

    });
</script>
{% endblock custom_js %}

student_management_app/templates/hod_template/add_subject_template.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Add Subject
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Subject</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_subject_save" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Subject Name </label>
                    <input type="text" class="form-control" name="subject_name" placeholder="Enter Subject">
                  </div>
                   <div class="form-group">
                    <label>Course </label>
                    <select class="form-control" name="course">
                        {% for course in courses %}
                          <option value="{{ course.id }}">{{ course.course_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Staff</label>
                    <select class="form-control" name="staff">
                        {% for staff in staffs %}
                          <option value="{{ staff.id }}">{{ staff.first_name }} {{ staff.last_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Add Subject</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/hod_template/admin_profile.html
{% extends 'hod_template/base_template.html' %}
{% block page_title %}
Edit Profile
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Profile</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'admin_profile_save' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                  </div>
                  <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" value="{{ user.email }}" disabled="disabled">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}">
                  </div>
                  <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                  </div>
                   <div class="form-group">
                    <label>Change Password?</label>
                    <input type="text" class="form-control" name="password" placeholder="Fill Only If You want to Change Password">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Save Profile</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/hod_template/base_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>M.R.M High School</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "plugins/jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "plugins/summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    {% block custom_css %}{% endblock custom_css %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <h4 style="margin-left: 10px;margin-top: 5px;">M.R.M High School</h4>
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          Logout
        </a>
      </li>
    </ul>

    <!-- Right navbar links -->
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
    {% include 'hod_template/sidebar_template.html' with user=user id=id %}

  <!-- Content Wrapper. Contains page content -->
   <div class="content-wrapper">
       <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
            </h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'admin_home' %}">Home</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
     {% block main_content %}{% endblock main_content %}

  </div>
  <!-- /.content-wrapper -->
    {% include 'hod_template/footer.html' %}

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "dist/js/demo.js" %}"></script>

{% block custom_js %}
{% endblock custom_js %}

</body>
</html>